server:
  host: ":8081"
  timeout: 10s
database:
  port: "5432"
  user: "postgres"
  password: "alex1234"
  dbname: "postgres"
  #host: "localhost" -- local
  host: "postgres"
redis:
  #redis_address: "localhost:6379" -- local
  redis_address: "redis:6379"
  redis_password: ""
  redis_db: 0



#docker run -d --name alex-db1 -e POSTGRES_PASSWORD=alex1234 -v ${HOME}/pgdata/:/var/lib/postgresql/data -p 5438:5432 postgres