ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS shardkey VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS shardkey VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN IF NOT EXISTS shardkey VARCHAR(10) NOT NULL DEFAULT '';
